### ISSUE TITLE
Extension

### ISSUE THREAD

**Issue by wwsh** [julianstricker/ThumbnailBundle#2]
Hello!

Does the bundle support image extensions at all? I don't see any code responsible for concating the file extension in the controller.

I'm having various .jpg and .png files in the public/images folder and wanted to use your bundle, as the idea seems great.

Could you provide a solution for using your bundle with classic files with extensions?

Example filename: 3463f9eb8cd476d6151106b6c5b4bd8cb8472d02.png

**Comment by julianstricker** [comment]
Hello!
If you remove the import of the routing file (Step 4 in README.md) and add only the routes from Resources/config/routing.yml without *_extension than it should work:

`just_thumbnail:
    path:  /thumbnails/{mode}/{maxx}x{maxy}/{img}
    defaults: { _controller: JustThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxx: ~
        #maxy: ~
        img: ".+"

just_thumbnail_x:
    path:  /thumbnails/{mode}/{maxx}x/{img}
    defaults: { _controller: JustThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxx: ~
        img: ".+"

just_thumbnail_y:
    path:  /thumbnails/{mode}/x{maxy}/{img}
    defaults: { _controller: JustThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxy: ~
        img: ".+"`

**Comment by wwsh** [comment]
The idea worked. Thank you!
